Apply CNR comments.
opengeospatial/ogc-feat-geo-json pull request #44
Opened 2022-02-28 04:47 UTC by pvretano

2022-03-07 16:18 UTC, cportele requested changes
Meeting 2022-03-07: Merge as soon as the comments have been addressed.

2022-03-07 16:18 UTC, cportele commented on core/clause_6_introduction.adoc
> +NOTE: PAV Comment.  I added Carl's comments about provenance metadata and styling information but I am not sure they are relevant here.  There is nothing preventing someone from adding additional mem
Meeting 2022-03-07: Yes, these use cases are out-of-scope for JSON-FG and we should not add them in this document. We will limit the list to the topics that JSON-FG addresses. The key point is that we are not prohibiting others to add such information to a GeoJSON/JSON-FG document. @pvretano will remove the two bullets again.

2022-03-07 16:18 UTC, cportele commented on core/clause_5_conventions.adoc
> +NOTE: CNR Comment about this last paragraph: Is some clarification needed? From JSON schema: It is also best practice to include an $id property as a unique identifier for each schema. For now, just
Meeting 2022-03-07: Clarify that "$id" is specified in JSON Schema.

2022-03-07 16:18 UTC, cportele commented on core/clause_6_introduction.adoc
> +In the first scenario (API access), the client will typically request the JSON-FG representation of the feature using an HTTP header like `Accept: application/vnd.ogc.fg+json, application/geo+json;q=
JONS -> JSON

2022-03-07 16:18 UTC, cportele commented on core/clause_7_building_blocks.adoc
> +NOTE: CNR Comment: What is "This"?  This clause?  This(these) example(s)?
Meeting 2022-03-07: @cportele will resolve this.

2022-03-07 16:18 UTC, cportele commented on core/clause_7_building_blocks.adoc
> +NOTE: CNR Comment: What is "This"?  This clause?  This(these) example(s)?
Meeting 2022-03-07: Same as above - @cportele will fix this.

2022-03-07 17:14 UTC, cportele commented on core/clause_7_building_blocks.adoc
> +NOTE: CNR Comment: What is "This"?  This clause?  This(these) example(s)?
@pvretano - change the paragraph to:

"Dates and timestamps are the initial range of instant values. The range may be extended in the future to support additional use cases. Clients processing values of `time` must be prepared to receive other values. Clients may ignore values that they do not understand."

2022-05-02 15:08 UTC, pvretano commented
02-MAY-2022: @pvretano to address last few remaning comments from @cportele and then just go ahead and merge.

2022-05-16 11:54 UTC, cportele commented on core/clause_6_introduction.adoc
> +NOTE: PAV Comment.  I added Carl's comments about provenance metadata and styling information but I am not sure they are relevant here.  There is nothing preventing someone from adding additional mem
Resolved by 97ebaf7

2022-05-16 11:56 UTC, cportele commented on core/clause_6_introduction.adoc
> +In the first scenario (API access), the client will typically request the JSON-FG representation of the feature using an HTTP header like `Accept: application/vnd.ogc.fg+json, application/geo+json;q=
Resolved by 790ef68

2022-05-16 11:58 UTC, cportele commented on core/clause_7_building_blocks.adoc
> +NOTE: CNR Comment: What is "This"?  This clause?  This(these) example(s)?
Resolved by 2f1bd69

2022-05-16 11:58 UTC, cportele commented on core/clause_7_building_blocks.adoc
> +NOTE: CNR Comment: What is "This"?  This clause?  This(these) example(s)?
Resolved by 2f1bd69

2022-05-16 12:38 UTC, cportele commented on core/clause_5_conventions.adoc
> +NOTE: CNR Comment about this last paragraph: Is some clarification needed? From JSON schema: It is also best practice to include an $id property as a unique identifier for each schema. For now, just
Resolved by ae4a5ae

2022-05-16 12:44 UTC, merged